import json
import re
import time
from pathlib import Path
from typing import Optional, Set

import anthropic
from _utils import _call_with_retry, _load_checkpoint, _load_schema

MODEL = "claude-sonnet-4-6"
BASE_DELAY = 2.0
MAX_RETRIES = 3

INPUT_PATH = Path("data/predictions.jsonl")
OUTPUT_PATH = Path("data/llm_judge_labels.jsonl")
TABLES_PATH = Path("data/spider/tables.json")

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, the database schema, and a predicted SQL query, "
    "determine whether the predicted SQL correctly answers the question on this database. "
    "Be rigorous: consider missing WHERE clauses, wrong aggregations, incorrect JOINs, "
    "and column or table names that do not exist in the schema."
)

USER_TEMPLATE = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Predicted SQL: {predicted_sql}

Respond with JSON only:
{{"label": <0 or 1>}}

Where label=1 means the SQL correctly answers the question, label=0 means incorrect."""


def _parse_label(text: str) -> Optional[int]:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        data = json.loads(match.group())
        label = int(data["label"])
        if label not in (0, 1):
            return None
        return label
    except (json.JSONDecodeError, KeyError, ValueError):
        return None


def main() -> None:
    schemas = _load_schema(TABLES_PATH)
    examples = [json.loads(line) for line in open(INPUT_PATH) if line.strip()]

    processed: Set[str] = _load_checkpoint(OUTPUT_PATH)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    client = anthropic.Anthropic()
    with open(OUTPUT_PATH, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")
            user_prompt = USER_TEMPLATE.format(
                db_id=ex["db_id"],
                schema=schemas[ex["db_id"]],
                question=ex["question"],
                predicted_sql=ex["predicted_sql"],
            )
            raw = _call_with_retry(
                client,
                max_retries=MAX_RETRIES,
                base_delay=BASE_DELAY,
                model=MODEL,
                max_tokens=64,
                temperature=0.0,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            if raw is None:
                continue
            label = _parse_label(raw)
            if label is None:
                print(f"    Could not parse label from: {raw!r}")
                continue
            record = {"example_id": ex["example_id"], "llm_judge_label": label}
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            time.sleep(0.3)


if __name__ == "__main__":
    main()
