version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - $HOME/.cargo/bin/uv sync --group doc
    - $HOME/.cargo/bin/uv run mkdocs build

mkdocs:
  configuration: mkdocs.yml
