site_name: Glide
theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      execute: false
      include_source: true

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Quickstart: notebooks/quickstart.ipynb
  - Why use Glide ?: notebooks/why_use_glide.ipynb
  - Performance estimation: performance-estimation/guide.md
  - API Reference: api/index.md
