site_name: Glide
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - mkdocs-jupyter:
      include_source: true
      execute: false # true

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.ipynb
  - Tutorials:
    - Estimate Hallucination rate at low cost with PPI++: tutorials/ppi.ipynb
    - ASI Tutorial: tutorials/asi.ipynb
  - User Guide: user_guide.md
  - Deep Dive:
    - Scientific Validation of PPI: deep_dive/ppi_validation.ipynb
    - Scientific Validation of ASI: deep_dive/asi_validation.ipynb
  - Contributing: contributing.md
  - API Reference: api/index.md
