"""
Generate LLM judge labels for Spider predictions using claude-sonnet-4-6.

Run from the repo root after generate_predictions.py:
    python spider_case_study/scripts/generate_llm_judge_labels.py

Requires:
    ANTHROPIC_API_KEY environment variable
    spider_case_study/data/predictions.jsonl (from generate_predictions.py)
"""

import json
import re
import time
from pathlib import Path
from typing import Dict, Optional, Set

import anthropic

MODEL = "claude-sonnet-4-6"
BASE_DELAY = 2.0
MAX_RETRIES = 3

INPUT_PATH = Path(__file__).parent.parent / "data" / "predictions.jsonl"
OUTPUT_PATH = Path(__file__).parent.parent / "data" / "llm_judge_labels.jsonl"

SYSTEM_PROMPT = (
    "You are evaluating the correctness of SQL queries generated by an AI assistant. "
    "Given a question and the predicted SQL, determine if the predicted SQL is semantically equivalent "
    "to the natural language question. Note: no database schema is provided — evaluate based solely on "
    "the question intent and the SQL structure."
)

USER_TEMPLATE = """\
Question: {question}
Database: {db_id}
Predicted SQL: {predicted_sql}

Respond with JSON only:
{{"label": <0 or 1>, "reasoning": "<brief explanation>"}}

Where label=1 means the predicted SQL is correct (semantically equivalent to the natural language question),
and label=0 means incorrect.
"""


def _call_with_retry(
    client: anthropic.Anthropic,
    max_retries: int = MAX_RETRIES,
    base_delay: float = BASE_DELAY,
    **kwargs,
) -> Optional[str]:
    for attempt in range(max_retries):
        try:
            response = client.messages.create(**kwargs)
            return response.content[0].text
        except anthropic.RateLimitError:
            delay = base_delay * (2**attempt)
            print(f"  Rate limit hit, retrying in {delay:.0f}s (attempt {attempt + 1}/{max_retries})")
            time.sleep(delay)
        except anthropic.APIStatusError as exc:
            if exc.status_code >= 500:
                delay = base_delay * (2**attempt)
                print(f"  API error {exc.status_code}, retrying in {delay:.0f}s (attempt {attempt + 1}/{max_retries})")
                time.sleep(delay)
            else:
                print(f"  Non-retryable API error {exc.status_code}: {exc}")
                return None
    print(f"  Exhausted {max_retries} retries, skipping row.")
    return None


def _parse_label(text: str) -> Optional[Dict]:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        data = json.loads(match.group())
        label = int(data["label"])
        if label not in (0, 1):
            return None
        return {"label": label, "reasoning": str(data.get("reasoning", ""))}
    except (json.JSONDecodeError, KeyError, ValueError):
        return None


def _load_checkpoint(path: Path) -> Set[str]:
    if not path.exists():
        return set()
    processed: Set[str] = set()
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                processed.add(json.loads(line)["example_id"])
            except (json.JSONDecodeError, KeyError):
                pass
    return processed


def _load_predictions() -> list:
    if not INPUT_PATH.exists():
        raise FileNotFoundError(f"Predictions file not found: {INPUT_PATH}\nRun generate_predictions.py first.")
    examples = []
    with open(INPUT_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))
    return examples


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    examples = _load_predictions()
    print(f"Loaded {len(examples)} predictions from {INPUT_PATH}")

    processed = _load_checkpoint(OUTPUT_PATH)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Already processed: {len(processed)} — remaining: {len(remaining)}")

    if not remaining:
        print("All examples already processed. Nothing to do.")
        return

    client = anthropic.Anthropic()

    with open(OUTPUT_PATH, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")

            user_prompt = USER_TEMPLATE.format(
                question=ex["question"],
                db_id=ex["db_id"],
                predicted_sql=ex["predicted_sql"],
            )

            response_text = _call_with_retry(
                client,
                model=MODEL,
                max_tokens=256,
                temperature=0.0,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )

            if response_text is None:
                print(f"    Skipping {ex['example_id']} after exhausted retries.")
                continue

            parsed = _parse_label(response_text)
            if parsed is None:
                print(f"    JSON parse error for {ex['example_id']}, skipping. Raw: {response_text[:120]!r}")
                continue

            record = {
                "example_id": ex["example_id"],
                "llm_judge_label": parsed["label"],
                "llm_judge_reasoning": parsed["reasoning"],
            }
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()

            time.sleep(0.3)

    total = sum(1 for _ in open(OUTPUT_PATH))
    print(f"\nDone. {OUTPUT_PATH} contains {total} records.")


if __name__ == "__main__":
    main()
