import argparse
import json
import time
from pathlib import Path
from typing import Set

from _utils import _load_checkpoint, _load_schemas, anthropic_judge, openai_judge
from dotenv import load_dotenv

load_dotenv()

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, a database schema, a reference gold SQL query, and a predicted SQL query, "
    "judge whether the predicted query correctly answers the question. "
    "The gold query is a known-correct reference, not the only acceptable answer: the predicted query may differ "
    "in column order, include extra non-essential columns, use different but equivalent joins, or take an "
    "alternative valid approach and still be correct. "
    "Label 0 only if the predicted query applies wrong filters, uses incorrect aggregations, omits critical data, "
    "or otherwise fails to answer the question."
)

USER_TEMPLATE = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Gold SQL: {gold_sql}
Predicted SQL: {predicted_sql}

Submit label 1 if the predicted SQL correctly answers the question, 0 if it does not."""


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Run an LLM judge comparing predicted SQL against gold SQL. "
            "Outputs a checkpointed JSONL file and can be safely interrupted and resumed. "
            "Requires ANTHROPIC_API_KEY or OPENAI_API_KEY depending on the provider."
        )
    )
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai"],
        default="openai",
        help="LLM provider to use. (default: openai)",
    )
    parser.add_argument(
        "--model",
        default="gpt-5.4",
        help="Model name passed to the provider API. (default: gpt-5.4)",
    )
    parser.add_argument(
        "--base-delay",
        type=float,
        default=2.0,
        help="Base delay in seconds for exponential backoff between retries. (default: 2.0)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of API call retries on failure. (default: 3)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Path to the input JSONL file containing predictions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output JSONL file for ground truth labels; used as a checkpoint. "
            "(default: data/ground_truths_by_<model>_on_<input>.jsonl)"
        ),
    )
    parser.add_argument(
        "--tables",
        type=Path,
        default=Path("data/spider/tables.json"),
        help="Path to the Spider tables.json schema file. (default: data/spider/tables.json)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Seconds to sleep between API calls to avoid rate limits. (default: 0.0)",
    )
    args = parser.parse_args()

    if args.output is None:
        model_slug = args.model.replace("/", "-")
        input_stem = args.input.stem
        args.output = Path(f"data/ground_truths_by_{model_slug}_on_{input_stem}.jsonl")

    schemas = _load_schemas(args.tables)
    examples = [json.loads(line) for line in open(args.input) if line.strip()]

    processed: Set[str] = _load_checkpoint(args.output)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    if args.provider == "anthropic":
        judge = anthropic_judge(args.model, args.base_delay, args.max_retries, SYSTEM_PROMPT)
    else:
        judge = openai_judge(args.model, args.base_delay, args.max_retries, SYSTEM_PROMPT)

    n_written = 0
    with open(args.output, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")
            user_prompt = USER_TEMPLATE.format(
                db_id=ex["db_id"],
                schema=schemas[ex["db_id"]],
                question=ex["question"],
                gold_sql=ex["gold_sql"],
                predicted_sql=ex["predicted_sql"],
            )
            result = judge([{"role": "user", "content": user_prompt}])
            if result is None:
                continue
            label, _ = result
            record = {"example_id": ex["example_id"], "ground_truth_label": label}
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            n_written += 1
            time.sleep(args.sleep)
    print(f"Done. {n_written} records written to {args.output.resolve()}")


if __name__ == "__main__":
    main()
