import argparse
import json
import time
from pathlib import Path
from typing import Set

from _utils import _load_checkpoint, _load_schemas, anthropic_judge, openai_judge
from dotenv import load_dotenv

load_dotenv()

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, the database schema, and a predicted SQL query, "
    "determine whether the predicted SQL correctly answers the question on this database. "
    "Be rigorous: for each requirement stated in the question, verify both that it is present in the query "
    "and that it is correctly implemented. "
    "Pay attention to missing WHERE clauses, wrong aggregations, incorrect JOINs, "
    "and column or table names that do not exist in the schema. "
    "Label a query as correct only if it fully and faithfully satisfies every requirement of the question."
)

USER_TEMPLATE = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Predicted SQL: {predicted_sql}

Submit label 1 if the SQL correctly answers the question, 0 if it does not."""

USER_TEMPLATE_WITH_REASONING = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Predicted SQL: {predicted_sql}

In one or two sentences, note what might be wrong or missing in the predicted SQL, \
then label it 1 if it correctly answers the question, 0 if it does not."""


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Run an LLM judge on Spider predictions. "
            "Outputs a checkpointed JSONL file and can be safely interrupted and resumed. "
            "Requires ANTHROPIC_API_KEY or OPENAI_API_KEY depending on the provider."
        )
    )
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai"],
        default="openai",
        help="LLM provider to use. (default: openai)",
    )
    parser.add_argument(
        "--model",
        default="gpt-5.4-mini",
        help="Model name passed to the provider API. (default: gpt-5.4-mini)",
    )
    parser.add_argument(
        "--base-delay",
        type=float,
        default=2.0,
        help="Base delay in seconds for exponential backoff between retries. (default: 2.0)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of API call retries on failure. (default: 3)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Path to the input JSONL file containing predictions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output JSONL file for LLM judge labels; used as a checkpoint. "
            "(default: data/llm_judge_labels_by_<model>_on_<input>.jsonl)"
        ),
    )
    parser.add_argument(
        "--tables",
        type=Path,
        default=Path("data/spider/tables.json"),
        help="Path to the Spider tables.json schema file. (default: data/spider/tables.json)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Seconds to sleep between API calls to avoid rate limits. (default: 0.0)",
    )
    args = parser.parse_args()

    if args.output is None:
        model_slug = args.model.replace("/", "-")
        input_stem = args.input.stem
        args.output = Path(f"data/llm_judge_labels_by_{model_slug}_on_{input_stem}.jsonl")

    schemas = _load_schemas(args.tables)
    examples = [json.loads(line) for line in open(args.input) if line.strip()]

    processed: Set[str] = _load_checkpoint(args.output)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    if args.provider == "anthropic":
        judge = anthropic_judge(args.model, args.base_delay, args.max_retries, SYSTEM_PROMPT, with_reasoning=True)
    else:
        judge = openai_judge(args.model, args.base_delay, args.max_retries, SYSTEM_PROMPT, with_reasoning=True)
    template = USER_TEMPLATE_WITH_REASONING

    n_written = 0
    with open(args.output, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")
            user_prompt = template.format(
                db_id=ex["db_id"],
                schema=schemas[ex["db_id"]],
                question=ex["question"],
                predicted_sql=ex["predicted_sql"],
            )
            result = judge([{"role": "user", "content": user_prompt}])
            if result is None:
                continue
            label, reasoning = result
            record = {"example_id": ex["example_id"], "llm_judge_label": label}
            if reasoning is not None:
                record["reasoning"] = reasoning
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            n_written += 1
            time.sleep(args.sleep)
    print(f"Done. {n_written} records written to {args.output.resolve()}")


if __name__ == "__main__":
    main()
