import argparse
import json
import sqlite3
import time
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from _utils import (
    SQL_CORRECTNESS_CRITERIA,
    _load_checkpoint,
    _load_schemas,
    _strip_markdown_fence,
    judge,
)

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, a database schema, a gold SQL query, and a predicted SQL query, "
    "judge whether the predicted query correctly answers the question. "
    "The gold query is one valid reference, not the only acceptable answer."
)

USER_TEMPLATE = (
    "Database: {db_id}\n\n"
    "Schema:\n{schema}\n\n"
    "Question: {question}\n"
    "Gold SQL: {gold_sql}\n"
    "Predicted SQL: {predicted_sql}\n\n"
    + SQL_CORRECTNESS_CRITERIA
    + "\n\nIn one or two sentences, reason about whether the predicted SQL correctly answers the question,"
    " then label it 1 if it does, 0 if it does not."
)


def _execute_query(db_path: Path, sql: str) -> Tuple[Optional[List], Optional[str]]:
    if not db_path.exists():
        return None, f"db_error: database file not found: {db_path}"

    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as exc:
        return None, f"db_error: {exc}"

    try:
        cursor = conn.cursor()
        cursor.execute(sql)
        rows = cursor.fetchall()
        result = sorted(rows, key=str)
        return result, None
    except sqlite3.Error as exc:
        return None, f"sql_error: {exc}"
    finally:
        conn.close()


def _compare_outputs(db_path: Path, gold_sql: str, predicted_sql: str) -> Tuple[bool, Optional[str], Optional[str]]:
    gold_rows, gold_error = _execute_query(db_path, gold_sql)
    predicted_rows, predicted_error = _execute_query(db_path, _strip_markdown_fence(predicted_sql))

    if gold_error is not None or predicted_error is not None:
        return False, gold_error, predicted_error

    outputs_match = predicted_rows == gold_rows
    return outputs_match, None, None


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Run a hybrid SQL evaluator: first compare query outputs directly, then fall back to an LLM judge "
            "when outputs differ. Outputs a checkpointed JSONL file and can be safely interrupted and resumed. "
            "Requires OPENAI_API_KEY."
        )
    )
    parser.add_argument(
        "--model",
        default="gpt-5.4",
        help="OpenAI model name. (default: gpt-5.4)",
    )
    parser.add_argument(
        "--base-delay",
        type=float,
        default=2.0,
        help="Base delay in seconds for exponential backoff between retries. (default: 2.0)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of API call retries on failure. (default: 3)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Path to the input JSONL file containing predictions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output JSONL file for ground truth labels; used as a checkpoint. "
            "(default: data/ground_truths_by_<model>_on_<input>.jsonl)"
        ),
    )
    parser.add_argument(
        "--tables",
        type=Path,
        default=Path("data/spider/tables.json"),
        help="Path to the Spider tables.json schema file. (default: data/spider/tables.json)",
    )
    parser.add_argument(
        "--db-root",
        type=Path,
        default=Path("data/spider"),
        help="Spider root or its 'database' subdirectory. (default: data/spider)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Seconds to sleep between API calls to avoid rate limits. (default: 0.0)",
    )
    args = parser.parse_args()

    if args.output is None:
        model_slug = args.model.replace("/", "-")
        input_stem = args.input.stem
        args.output = Path(f"data/ground_truths_by_{model_slug}_on_{input_stem}.jsonl")

    db_root = args.db_root / "database" if (args.db_root / "database").is_dir() else args.db_root
    schemas = _load_schemas(args.tables)
    examples = [json.loads(line) for line in open(args.input) if line.strip()]

    processed: Set[str] = _load_checkpoint(args.output)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    llm_judge = judge(args.model, args.base_delay, args.max_retries, SYSTEM_PROMPT)

    n_written = 0
    n_judge_calls = 0
    with open(args.output, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})", end="")
            db_path = db_root / ex["db_id"] / f"{ex['db_id']}.sqlite"
            outputs_match, gold_execution_error, predicted_execution_error = _compare_outputs(
                db_path, ex["gold_sql"], ex["predicted_sql"]
            )

            record: Dict = {"example_id": ex["example_id"], "outputs_match": outputs_match}
            if gold_execution_error is not None:
                record["gold_execution_error"] = gold_execution_error
            if predicted_execution_error is not None:
                record["predicted_execution_error"] = predicted_execution_error

            if outputs_match:
                print(" [match]")
                record["ground_truth_label"] = 1
                record["reasoning"] = ""
            else:
                print(" [mismatch -> LLM judge]")
                user_prompt = USER_TEMPLATE.format(
                    db_id=ex["db_id"],
                    schema=schemas[ex["db_id"]],
                    question=ex["question"],
                    gold_sql=ex["gold_sql"],
                    predicted_sql=ex["predicted_sql"],
                )
                result = llm_judge([{"role": "user", "content": user_prompt}])
                if result is None:
                    continue
                label, reasoning = result
                record["ground_truth_label"] = label
                record["reasoning"] = reasoning or ""
                n_judge_calls += 1
                time.sleep(args.sleep)

            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            n_written += 1

    print(f"Done. {n_written} records written to {args.output.resolve()} ({n_judge_calls} LLM judge calls)")


if __name__ == "__main__":
    main()
