import argparse
import json
import re
import time
from pathlib import Path
from typing import Callable, Dict, List, Optional, Set

import anthropic
import openai
from _utils import _call_with_retry, _load_checkpoint, _load_schema
from dotenv import load_dotenv

load_dotenv()

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, the database schema, and a predicted SQL query, "
    "determine whether the predicted SQL correctly answers the question on this database. "
    "Be rigorous: pay attention to missing WHERE clauses, wrong aggregations, incorrect JOINs, "
    "and column or table names that do not exist in the schema. "
    "Your response must be a single digit: 0 or 1. Output nothing else."
)

USER_TEMPLATE = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Predicted SQL: {predicted_sql}

Output 1 if the SQL correctly answers the question, 0 if it does not. Output only 0 or 1
and absolutely nothing more."""


def _parse_label(text: str) -> Optional[int]:
    stripped = text.strip()
    if stripped in ("0", "1"):
        return int(stripped)
    match = re.search(r"\b([01])\b", stripped)
    if match:
        return int(match.group(1))
    return None


def anthropic_judge(model: str, base_delay: float, max_retries: int) -> Callable[[List[Dict]], Optional[str]]:
    client = anthropic.Anthropic()

    def judge(messages: List[Dict]) -> Optional[str]:
        return _call_with_retry(
            client,
            max_retries=max_retries,
            base_delay=base_delay,
            model=model,
            max_tokens=64,
            temperature=0.0,
            system=SYSTEM_PROMPT,
            messages=messages,
        )

    return judge


def openai_judge(model: str, base_delay: float, max_retries: int) -> Callable[[List[Dict]], Optional[str]]:
    client = openai.OpenAI()

    def judge(messages: List[Dict]) -> Optional[str]:
        system_messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        for attempt in range(max_retries):
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=system_messages + messages,
                    # max_tokens=64,
                    temperature=0.0,
                )
                return response.choices[0].message.content
            except Exception as e:
                if attempt < max_retries - 1:
                    time.sleep(base_delay * (2**attempt))
                else:
                    print(f"  Error after {max_retries} attempts: {e}")
        return None

    return judge


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Run an LLM judge on Spider predictions. "
            "Outputs a checkpointed JSONL file and can be safely interrupted and resumed. "
            "Requires ANTHROPIC_API_KEY or OPENAI_API_KEY depending on the provider."
        )
    )
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai"],
        default="anthropic",
        help="LLM provider to use. (default: anthropic)",
    )
    parser.add_argument(
        "--model",
        default="claude-sonnet-4-6",
        help="Model name passed to the provider API. (default: claude-sonnet-4-6)",
    )
    parser.add_argument(
        "--base-delay",
        type=float,
        default=2.0,
        help="Base delay in seconds for exponential backoff between retries. (default: 2.0)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of API call retries on failure. (default: 3)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/predictions.jsonl"),
        help="Path to the input JSONL file containing predictions. (default: data/predictions.jsonl)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/llm_judge_labels.jsonl"),
        help="Output JSONL file for LLM judge labels; used as a checkpoint. (default: data/llm_judge_labels.jsonl)",
    )
    parser.add_argument(
        "--tables",
        type=Path,
        default=Path("data/spider/tables.json"),
        help="Path to the Spider tables.json schema file. (default: data/spider/tables.json)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Seconds to sleep between API calls to avoid rate limits. (default: 0.1)",
    )
    args = parser.parse_args()

    schemas = _load_schema(args.tables)
    examples = [json.loads(line) for line in open(args.input) if line.strip()]

    processed: Set[str] = _load_checkpoint(args.output)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    if args.provider == "anthropic":
        judge = anthropic_judge(args.model, args.base_delay, args.max_retries)
    else:
        judge = openai_judge(args.model, args.base_delay, args.max_retries)

    with open(args.output, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")
            user_prompt = USER_TEMPLATE.format(
                db_id=ex["db_id"],
                schema=schemas[ex["db_id"]],
                question=ex["question"],
                predicted_sql=ex["predicted_sql"],
            )
            raw = judge([{"role": "user", "content": user_prompt}])
            if raw is None:
                continue
            label = _parse_label(raw)
            if label is None:
                print(f"    Could not parse label from: {raw!r}")
                continue
            record = {"example_id": ex["example_id"], "llm_judge_label": label}
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            time.sleep(args.sleep)


if __name__ == "__main__":
    main()
