import argparse
import json
import time
from pathlib import Path
from typing import Callable, Dict, List, Optional, Set

import anthropic
import openai
from _utils import _load_checkpoint, _load_schema
from dotenv import load_dotenv

load_dotenv()

SYSTEM_PROMPT = (
    "You are evaluating SQL queries generated by an AI assistant. "
    "Given a natural language question, the database schema, and a predicted SQL query, "
    "determine whether the predicted SQL correctly answers the question on this database. "
    "Be rigorous: pay attention to missing WHERE clauses, wrong aggregations, incorrect JOINs, "
    "and column or table names that do not exist in the schema."
)

USER_TEMPLATE = """\
Database: {db_id}

Schema:
{schema}

Question: {question}
Predicted SQL: {predicted_sql}

Submit label 1 if the SQL correctly answers the question, 0 if it does not."""

_ANTHROPIC_LABEL_TOOL = {
    "name": "submit_label",
    "description": "Submit the correctness label for the predicted SQL query.",
    "input_schema": {
        "type": "object",
        "properties": {
            "label": {
                "type": "integer",
                "enum": [0, 1],
                "description": "1 if the SQL correctly answers the question, 0 otherwise.",
            }
        },
        "required": ["label"],
    },
}

_OPENAI_LABEL_TOOL = {
    "type": "function",
    "strict": True,
    "function": {
        "name": "submit_label",
        "description": "Submit the correctness label for the predicted SQL query.",
        "parameters": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "integer",
                    "enum": [0, 1],
                    "description": "1 if the SQL correctly answers the question, 0 otherwise.",
                }
            },
            "required": ["label"],
            "additionalProperties": False,
        },
    },
}


def anthropic_judge(model: str, base_delay: float, max_retries: int) -> Callable[[List[Dict]], Optional[int]]:
    client = anthropic.Anthropic()

    def judge(messages: List[Dict]) -> Optional[int]:
        for attempt in range(max_retries):
            try:
                response = client.messages.create(
                    model=model,
                    max_tokens=64,
                    temperature=0.0,
                    system=SYSTEM_PROMPT,
                    tools=[_ANTHROPIC_LABEL_TOOL],
                    tool_choice={"type": "tool", "name": "submit_label"},
                    messages=messages,
                )
                tool_use = next(b for b in response.content if b.type == "tool_use")
                return int(tool_use.input["label"])
            except Exception as e:
                if attempt < max_retries - 1:
                    time.sleep(base_delay * (2**attempt))
                else:
                    print(f"  Error after {max_retries} attempts: {e}")
        return None

    return judge


def openai_judge(model: str, base_delay: float, max_retries: int) -> Callable[[List[Dict]], Optional[int]]:
    client = openai.OpenAI()

    def judge(messages: List[Dict]) -> Optional[int]:
        system_messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        for attempt in range(max_retries):
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=system_messages + messages,
                    temperature=0.0,
                    tools=[_OPENAI_LABEL_TOOL],
                    tool_choice={"type": "function", "function": {"name": "submit_label"}},
                )
                args = json.loads(response.choices[0].message.tool_calls[0].function.arguments)
                return int(args["label"])
            except Exception as e:
                if attempt < max_retries - 1:
                    time.sleep(base_delay * (2**attempt))
                else:
                    print(f"  Error after {max_retries} attempts: {e}")
        return None

    return judge


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Run an LLM judge on Spider predictions. "
            "Outputs a checkpointed JSONL file and can be safely interrupted and resumed. "
            "Requires ANTHROPIC_API_KEY or OPENAI_API_KEY depending on the provider."
        )
    )
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai"],
        default="anthropic",
        help="LLM provider to use. (default: anthropic)",
    )
    parser.add_argument(
        "--model",
        default="claude-sonnet-4-6",
        help="Model name passed to the provider API. (default: claude-sonnet-4-6)",
    )
    parser.add_argument(
        "--base-delay",
        type=float,
        default=2.0,
        help="Base delay in seconds for exponential backoff between retries. (default: 2.0)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of API call retries on failure. (default: 3)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Path to the input JSONL file containing predictions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/llm_judge_labels.jsonl"),
        help="Output JSONL file for LLM judge labels; used as a checkpoint. (default: data/llm_judge_labels.jsonl)",
    )
    parser.add_argument(
        "--tables",
        type=Path,
        default=Path("data/spider/tables.json"),
        help="Path to the Spider tables.json schema file. (default: data/spider/tables.json)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Seconds to sleep between API calls to avoid rate limits. (default: 0.0)",
    )
    args = parser.parse_args()

    schemas = _load_schema(args.tables)
    examples = [json.loads(line) for line in open(args.input) if line.strip()]

    processed: Set[str] = _load_checkpoint(args.output)
    remaining = [ex for ex in examples if ex["example_id"] not in processed]
    print(f"Selected {len(examples)} examples -- already processed: {len(processed)}, remaining: {len(remaining)}")

    if args.provider == "anthropic":
        judge = anthropic_judge(args.model, args.base_delay, args.max_retries)
    else:
        judge = openai_judge(args.model, args.base_delay, args.max_retries)

    n_written = 0
    with open(args.output, "a") as out_f:
        for i, ex in enumerate(remaining):
            print(f"  [{i + 1}/{len(remaining)}] {ex['example_id']} ({ex['db_id']})")
            user_prompt = USER_TEMPLATE.format(
                db_id=ex["db_id"],
                schema=schemas[ex["db_id"]],
                question=ex["question"],
                predicted_sql=ex["predicted_sql"],
            )
            label = judge([{"role": "user", "content": user_prompt}])
            if label is None:
                continue
            record = {"example_id": ex["example_id"], "llm_judge_label": label}
            out_f.write(json.dumps(record) + "\n")
            out_f.flush()
            n_written += 1
            time.sleep(args.sleep)
    print(f"Done. {n_written} records written to {args.output.resolve()}")


if __name__ == "__main__":
    main()
