name: Code quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7.4.0

      - name: Install dependencies
        run: make venv

      - name: Lint
        run: make lint

      - name: Type check
        run: make type-check

      - name: Coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7.4.0

      - name: Install dependencies
        run: make venv

      - name: Test notebooks
        run: make test-notebooks