name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - "v*"         # automated PyPi publish on tag push of the form vX.Y.Z
  workflow_dispatch: # manual TestPyPI publish

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7.4.0

      - name: Build a binary wheel and a source tarball
        run: make build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v7.0.0
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: [build]
    runs-on: ubuntu-latest
    # NOTE: create a GitHub Environment named `pypi` in your repo settings
    # Make sure to update the pypi Trusted Publishers in the settings of your PyPI account
    environment:
      name: pypi
      url: https://pypi.org/project/glide-py/
    permissions:
      id-token: write  # mandatory for Trusted Publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          verbose: true

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: [build]
    if: github.event_name == 'workflow_dispatch'  # only publish to TestPyPI on manual trigger
    runs-on: ubuntu-latest
    # NOTE: create a GitHub Environment named `testpypi` in your repo settings
    # Make sure to update the testpypi Trusted Publishers in the settings of your TestPyPI account
    environment:
      name: testpypi
      url: https://test.pypi.org/project/glide-py/
    permissions:
      id-token: write  # mandatory for Trusted Publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true